export const Props =  {
  direction: 'direction',
  fillStyle: 'fillStyle',
  filter: 'filter',
  font: 'font',
  fontKerning: 'fontKerning',
  fontStretch: 'fontStretch',
  fontVariantCaps: 'fontVariantCaps',
  globalAlpha: 'globalAlpha',
  globalCompositeOperation: 'globalCompositeOperation',
  imageSmoothingEnabled: 'imageSmoothingEnabled',
  imageSmoothingQuality: 'imageSmoothingQuality',
  letterSpacing: 'letterSpacing',
  lineCap: 'lineCap',
  lineDashOffset: 'lineDashOffset',
  lineJoin: 'lineJoin',
  lineWidth: 'lineWidth',
  miterLimit: 'miterLimit',
  shadowBlur: 'shadowBlur',
  shadowColor: 'shadowColor',
  shadowOffsetX: 'shadowOffsetX',
  shadowOffsetY: 'shadowOffsetY',
  strokeStyle: 'strokeStyle',
  textAlign: 'textAlign',
  textBaseline: 'textBaseline',
  textRendering: 'textRendering',
  wordSpacing: 'wordSpacing',
};
